<?php

namespace Infojet\DevisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EcheanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcheanceRepository extends EntityRepository
{
	public function getEcheanceDisponibleForm()
	{
		$qb = $this->createQueryBuilder('t')
		->where('t.estDisponible = 1') ;
		return $qb;
	}
}
