<?php

namespace Infojet\DevisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RelationDevisAutreRiqsueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationDevisAutreRiqsueRepository extends EntityRepository
{
}
