<?php

namespace Infojet\DevisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RisqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RisqueRepository extends EntityRepository
{
	public function getRisqueDisponible()
	{
		$qb = $this->createQueryBuilder('t')
		->where('t.estDisponible = 1') ;
		
		return $qb->getQuery()
					->getResult();;
	}
}
