security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Abi\UtilisateurBundle\Entity\Utilisateur:
            algorithm : sha1
            iterations : 1
            encode_as_base64: false
    role_hierarchy:
        ROLE_GERANT: [ROLE_CLIENT]
        ROLE_ADMIN: [ROLE_GERANT]       
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity : {class:Abi\UtilisateurBundle\Entity\Utilisateur, property:mail}
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        main:
            pattern: /
            anonymous: true
            provider: main
            form_login:
                login_path: abi_utilisateur_login
                check_path: abi_utilisateur_login_check
            logout:
                path:   abi_utilisateur_logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
