Devis\DecennaleBundle\Entity\AbsClientCompliment:
    type: entity
    table: abs_client_compliment
    id:
        clcompId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: clcomp_id
            generator:
                strategy: IDENTITY
    fields:
        clcompRef:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: clcomp_ref
        clcompSociete:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: clcomp_societe
        clcompNumerovois:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: clcomp_numerovois
        clcompBatiment:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: clcomp_batiment
        clcompEscalier:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: clcomp_escalier
        clcompCode1:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: clcomp_code1
        clcompCode2:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: clcomp_code2
        clcompInterphone:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: clcomp_Interphone
        clcompEtage:
            type: string
            nullable: false
            length: 4
            fixed: false
            comment: ''
            column: clcomp_etage
        clcompPorte:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: clcomp_porte
        clcompRemarque:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: clcomp_remarque
        clcompEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: clcomp_etat
    lifecycleCallbacks: {  }
