Devis\DecennaleBundle\Entity\AbsClientDocuments:
    type: entity
    table: abs_client_documents
    id:
        docId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: doc_id
            generator:
                strategy: IDENTITY
    fields:
        docRef:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: doc_ref
        docTitre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: doc_titre
        docDocument:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: doc_document
        docExtension:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: doc_extension
        docDate:
            type: date
            nullable: false
            comment: ''
            column: doc_date
    lifecycleCallbacks: {  }
