Devis\DecennaleBundle\Entity\AbsCommentaire:
    type: entity
    table: abs_commentaire
    id:
        commentId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: comment_id
            generator:
                strategy: IDENTITY
    fields:
        commentRef:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: comment_ref
        commentCivilite:
            type: string
            nullable: false
            length: 4
            fixed: false
            comment: ''
            column: comment_civilite
        commentPrenom:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: comment_prenom
        commentNom:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: comment_nom
        commentEmail:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: comment_email
        commentText:
            type: string
            nullable: false
            length: 300
            fixed: false
            comment: ''
            column: comment_text
        commentEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: comment_etat
        commentDate:
            type: date
            nullable: false
            comment: ''
            column: comment_date
        commentNote:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: comment_note
    lifecycleCallbacks: {  }
