Devis\DecennaleBundle\Entity\AbsMessagdevis:
    type: entity
    table: abs_messagdevis
    id:
        devisId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: devis_id
            generator:
                strategy: IDENTITY
    fields:
        devisRefclient:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: devis_refclient
        devisRefdevis:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            column: devis_refdevis
        devisTypecontrat:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: devis_typecontrat
        devisEcheance:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: devis_echeance
        devisEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: devis_etat
        devisDate:
            type: date
            nullable: false
            comment: ''
            column: devis_date
    lifecycleCallbacks: {  }
