Devis\DecennaleBundle\Entity\AbsNav:
    type: entity
    table: abs_nav
    id:
        navId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nav_id
            generator:
                strategy: IDENTITY
    fields:
        navTitre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: nav_titre
        navUrl:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: nav_url
        navOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nav_ordre
        navType:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nav_type
        navEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nav_etat
    lifecycleCallbacks: {  }
