Devis\DecennaleBundle\Entity\AbsPub:
    type: entity
    table: abs_pub
    id:
        pubId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: pub_id
            generator:
                strategy: IDENTITY
    fields:
        pubPhrase:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: pub_phrase
        pubEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pub_etat
        pubDate:
            type: date
            nullable: false
            comment: ''
            column: pub_date
    lifecycleCallbacks: {  }
