Devis\DecennaleBundle\Entity\AbsPageEtiquete:
    type: entity
    table: abs_page_etiquete
    id:
        petqId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: petq_id
            generator:
                strategy: IDENTITY
    fields:
        petqRefetequette:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: petq_refetequette
        petqRefarticle:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: petq_refarticle
    lifecycleCallbacks: {  }
