Devis\DecennaleBundle\Entity\AbsPagePrix:
    type: entity
    table: abs_page_prix
    id:
        prixId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: prix_id
            generator:
                strategy: IDENTITY
    fields:
        prixRefarticle:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: prix_refarticle
        prixPrix:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: prix_prix
    lifecycleCallbacks: {  }
