Devis\DecennaleBundle\Entity\AbsPageExiste:
    type: entity
    table: abs_page_existe
    id:
        pgexitId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: pgexit_id
            generator:
                strategy: IDENTITY
    fields:
        pgexitRef:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pgexit_ref
        pgexitTitre:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: pgexit_titre
        pgexitDescription:
            type: string
            nullable: false
            length: 400
            fixed: false
            comment: ''
            column: pgexit_description
        pgexitSlug:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: pgexit_slug
        pgexitUrl:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: pgexit_url
        pgexitType:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: pgexit_type
        pgexitEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pgexit_etat
    lifecycleCallbacks: {  }
