Devis\DecennaleBundle\Entity\AbsPageSiteLogo:
    type: entity
    table: abs_page_site_logo
    id:
        pagelogoId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: pagelogo_id
            generator:
                strategy: IDENTITY
    fields:
        pagelogoRef:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pagelogo_ref
        pagelogoImg:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: pagelogo_img
        pagelogoEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pagelogo_etat
    lifecycleCallbacks: {  }
