Devis\DecennaleBundle\Entity\AbsReservation:
    type: entity
    table: abs_reservation
    id:
        revId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: rev_id
            generator:
                strategy: IDENTITY
    fields:
        revRefclient:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: rev_refclient
        revRefresrv:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: rev_refresrv
        revVilledepart:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: rev_villedepart
        revVilleariv:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: rev_villeariv
        revDateresev:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: rev_dateresev
        revHeureresev:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: rev_heureresev
        revNbperssone:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: rev_nbperssone
        revNbbagage:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: rev_nbbagage
        revDistance:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: rev_distance
        revPrix:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: rev_prix
        revMessage:
            type: string
            nullable: false
            length: 400
            fixed: false
            comment: ''
            column: rev_message
        revDate:
            type: date
            nullable: false
            comment: ''
            column: rev_date
        revEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: rev_etat
    lifecycleCallbacks: {  }
