Devis\DecennaleBundle\Entity\AbsStyleBackground:
    type: entity
    table: abs_style_background
    uniqueConstraints:
        bad_id:
            columns:
                - bad_id
    id:
        badId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: bad_id
            generator:
                strategy: IDENTITY
    fields:
        badStyle:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: bad_style
    lifecycleCallbacks: {  }
