Devis\DecennaleBundle\Entity\AbsSlider:
    type: entity
    table: abs_slider
    id:
        sliderId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: slider_id
            generator:
                strategy: IDENTITY
    fields:
        sliderTitre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: slider_titre
        sliderImg:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: slider_img
        sliderText:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: slider_text
        sliderUrlTitre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: slider_url_titre
        sliderUrl:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: slider_url
        sliderInfo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: slider_info
        sliderDate:
            type: date
            nullable: false
            comment: ''
            column: slider_date
    lifecycleCallbacks: {  }
