Devis\DecennaleBundle\Entity\AbsThemeModule:
    type: entity
    table: abs_theme_module
    id:
        thModuleId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: th_module_id
            generator:
                strategy: IDENTITY
    fields:
        thModuleTitre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: th_module_titre
        thModuleInfo:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: th_module_info
        thModuleOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: th_module_ordre
        thModuleUrl:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: th_module_url
        thModuleEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: th_module_etat
    lifecycleCallbacks: {  }
