Devis\DecennaleBundle\Entity\AbsThemeBackground:
    type: entity
    table: abs_theme_background
    id:
        backgroundId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: background_id
            generator:
                strategy: IDENTITY
    fields:
        backgroundImg:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: background_img
        backgroundEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: background_etat
    lifecycleCallbacks: {  }
