Devis\DecennaleBundle\Entity\AbsTarif:
    type: entity
    table: abs_tarif
    id:
        tarifId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: tarif_id
            generator:
                strategy: IDENTITY
    fields:
        tarifMin:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: tarif_min
        tarifMax:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: tarif_max
        tarifPrix:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: tarif_prix
        tarifEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: tarif_etat
    lifecycleCallbacks: {  }
