Devis\DecennaleBundle\Entity\Departements:
    type: entity
    table: departements
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        regionId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: region_id
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        numero:
            type: string
            nullable: false
            length: 5
            fixed: false
            comment: ''
            default: ''
    lifecycleCallbacks: {  }
