Devis\DecennaleBundle\Entity\DevisPdf:
    type: entity
    table: devis_pdf
    id:
        pdfId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: pdf_id
            generator:
                strategy: IDENTITY
    fields:
        pdfRefclient:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: pdf_refclient
        pdfRefdevis:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: pdf_refdevis
        pdfPdf:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: pdf_pdf
        pdfExtension:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: pdf_extension
        pdfEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pdf_etat
        pdfDate:
            type: date
            nullable: false
            comment: ''
            column: pdf_date
    lifecycleCallbacks: {  }
