Devis\DecennaleBundle\Entity\MdlNosServices:
    type: entity
    table: mdl_nos_services
    id:
        nservId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nserv_id
            generator:
                strategy: IDENTITY
    fields:
        nservTitre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: nserv_titre
        nservIcon:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nserv_icon
        nservTexte:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: nserv_texte
        nservOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nserv_ordre
        nservEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nserv_etat
    lifecycleCallbacks: {  }
