Devis\DecennaleBundle\Entity\MdlNosReferances:
    type: entity
    table: mdl_nos_referances
    id:
        nrefrId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nrefr_id
            generator:
                strategy: IDENTITY
    fields:
        nrefrTitre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: nrefr_titre
        nrefrIcon:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nrefr_icon
        nrefrTexte:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: nrefr_texte
        nrefrOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nrefr_ordre
        nrefrEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nrefr_etat
    lifecycleCallbacks: {  }
