Devis\DecennaleBundle\Entity\MdlNosDocument:
    type: entity
    table: mdl_nos_document
    id:
        docId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: doc_id
            generator:
                strategy: IDENTITY
    fields:
        docTitre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: doc_titre
        docDescription:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: doc_description
        docPdf:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: doc_pdf
        docExtention:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: doc_extention
        docDate:
            type: date
            nullable: false
            comment: ''
            column: doc_date
        docEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: doc_etat
    lifecycleCallbacks: {  }
