Devis\DecennaleBundle\Entity\MdlNosServicesImg:
    type: entity
    table: mdl_nos_services_img
    id:
        nsergId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nserg_id
            generator:
                strategy: IDENTITY
    fields:
        nsergTitre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: nserg_titre
        nsergDescription:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: nserg_description
        nsergOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nserg_ordre
        nsergImg:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: nserg_img
        nsergEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nserg_etat
    lifecycleCallbacks: {  }
