Devis\DecennaleBundle\Entity\MdlNewsImg:
    type: entity
    table: mdl_news_img
    uniqueConstraints:
        nig_id:
            columns:
                - nig_id
    id:
        nigId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nig_id
            generator:
                strategy: IDENTITY
    fields:
        nigImg:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: nig_img
        nigEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nig_etat
    lifecycleCallbacks: {  }
