Devis\DecennaleBundle\Entity\MdlNews:
    type: entity
    table: mdl_news
    id:
        newsId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: news_id
            generator:
                strategy: IDENTITY
    fields:
        newsTitre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: news_titre
        newsDescrition:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: news_descrition
        newsDetaille:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: news_detaille
        newsSlug:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: news_slug
        newsEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: news_etat
        newsDate:
            type: date
            nullable: false
            comment: ''
            column: news_date
    lifecycleCallbacks: {  }
