Devis\DecennaleBundle\Entity\MdlNosReferancesImg:
    type: entity
    table: mdl_nos_referances_img
    id:
        nrefrimgId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: nrefrimg_id
            generator:
                strategy: IDENTITY
    fields:
        nrefrimgRef:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nrefrimg_ref
        nrefrimgImg:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: nrefrimg_img
        nrefrimgEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: nrefrimg_etat
    lifecycleCallbacks: {  }
