Devis\DecennaleBundle\Entity\MdlTarification:
    type: entity
    table: mdl_tarification
    id:
        tarfId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: tarf_id
            generator:
                strategy: IDENTITY
    fields:
        tarfTitre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: tarf_titre
        tarfIcon:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: tarf_icon
        tarfTexte:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: tarf_texte
        tarfOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: tarf_ordre
        tarfEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: tarf_etat
    lifecycleCallbacks: {  }
