Devis\DecennaleBundle\Entity\MdMetier:
    type: entity
    table: md_metier
    id:
        mtId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: mt_id
            generator:
                strategy: IDENTITY
    fields:
        mtTitre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: mt_titre
        mtDescription:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: mt_description
        mtOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: mt_ordre
        mtImg:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: mt_img
        mtEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: mt_etat
    lifecycleCallbacks: {  }
