Devis\DecennaleBundle\Entity\Mdnosoffres:
    type: entity
    table: mdnosoffres
    id:
        offId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: off_id
            generator:
                strategy: IDENTITY
    fields:
        offRefart:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: off_refart
        offDescription:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: off_description
        offEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: off_etat
        offDate:
            type: date
            nullable: false
            comment: ''
            column: off_date
    lifecycleCallbacks: {  }
