Devis\DecennaleBundle\Entity\RealisationImage:
    type: entity
    table: realisation_image
    id:
        imgId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: img_id
            generator:
                strategy: IDENTITY
    fields:
        imgRef:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: img_ref
        imgImg:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: img_img
        imgOrdre:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: img_ordre
        imgInfo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: img_info
        imgEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: img_etat
    lifecycleCallbacks: {  }
