Devis\DecennaleBundle\Entity\Regions:
    type: entity
    table: regions
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
    lifecycleCallbacks: {  }
