Devis\DecennaleBundle\Entity\VoitureModele:
    type: entity
    table: voiture_modele
    id:
        idModele:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_modele
            generator:
                strategy: IDENTITY
    fields:
        catModele:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: cat_modele
        titreModele:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: titre_modele
        etatModele:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: etat_modele
    lifecycleCallbacks: {  }
