Devis\DecennaleBundle\Entity\ZaAssuraceCat:
    type: entity
    table: za_assurace_cat
    id:
        asscatId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: asscat_id
            generator:
                strategy: IDENTITY
    fields:
        asscatTitre:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: asscat_titre
        asscatDescription:
            type: string
            nullable: false
            length: 300
            fixed: false
            comment: ''
            column: asscat_description
        asscatEtat:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: asscat_etat
    lifecycleCallbacks: {  }
