<?php

namespace Abi\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientTempRepository extends EntityRepository
{
}
