<?php

namespace Proxies\__CG__\Abi\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsClientSociete extends \Abi\UtilisateurBundle\Entity\AbsClientSociete implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soId', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soRef', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soRaisonSocial', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soFormjuridique', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soDateDeCreation', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soSiret', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soNbSalarier', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soChiffreAffaire', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soEtat', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soId', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soRef', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soRaisonSocial', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soFormjuridique', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soDateDeCreation', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soSiret', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soNbSalarier', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soChiffreAffaire', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soEtat', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClientSociete' . "\0" . 'soDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsClientSociete $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSoID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoID', array());

        return parent::getSoID();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoID($soId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoID', array($soId));

        return parent::setSoID($soId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoRef', array());

        return parent::getSoRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoRef($soRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoRef', array($soRef));

        return parent::setSoRef($soRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoRaisonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoRaisonSocial', array());

        return parent::getSoRaisonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoRaisonSocial($soRaisonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoRaisonSocial', array($soRaisonSocial));

        return parent::setSoRaisonSocial($soRaisonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoFormjuridique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoFormjuridique', array());

        return parent::getSoFormjuridique();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoFormjuridique($soFormjuridique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoFormjuridique', array($soFormjuridique));

        return parent::setSoFormjuridique($soFormjuridique);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoDateDeCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoDateDeCreation', array());

        return parent::getSoDateDeCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoDateDeCreation($soDateDeCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoDateDeCreation', array($soDateDeCreation));

        return parent::setSoDateDeCreation($soDateDeCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoSiret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoSiret', array());

        return parent::getSoSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoSiret($soSiret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoSiret', array($soSiret));

        return parent::setSoSiret($soSiret);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoNbSalarier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoNbSalarier', array());

        return parent::getSoNbSalarier();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoNbSalarier($soNbSalarier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoNbSalarier', array($soNbSalarier));

        return parent::setSoNbSalarier($soNbSalarier);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoChiffreAffaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoChiffreAffaire', array());

        return parent::getSoChiffreAffaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoChiffreAffaire($soChiffreAffaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoChiffreAffaire', array($soChiffreAffaire));

        return parent::setSoChiffreAffaire($soChiffreAffaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoEtat', array());

        return parent::getSoEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoEtat($soEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoEtat', array($soEtat));

        return parent::setSoEtat($soEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoDate', array());

        return parent::getSoDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoDate($soDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoDate', array($soDate));

        return parent::setSoDate($soDate);
    }

}
