<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MdlNosReferances extends \Abi\RoutineBundle\Entity\MdlNosReferances implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosReferances' . "\0" . 'nrefrEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MdlNosReferances $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNrefrId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNrefrId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrefrId', array());

        return parent::getNrefrId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrefrTitre($nrefrTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrefrTitre', array($nrefrTitre));

        return parent::setNrefrTitre($nrefrTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrefrTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrefrTitre', array());

        return parent::getNrefrTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrefrIcon($nrefrIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrefrIcon', array($nrefrIcon));

        return parent::setNrefrIcon($nrefrIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrefrIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrefrIcon', array());

        return parent::getNrefrIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrefrTexte($nrefrTexte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrefrTexte', array($nrefrTexte));

        return parent::setNrefrTexte($nrefrTexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrefrTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrefrTexte', array());

        return parent::getNrefrTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrefrOrdre($nrefrOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrefrOrdre', array($nrefrOrdre));

        return parent::setNrefrOrdre($nrefrOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrefrOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrefrOrdre', array());

        return parent::getNrefrOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrefrEtat($nrefrEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrefrEtat', array($nrefrEtat));

        return parent::setNrefrEtat($nrefrEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrefrEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrefrEtat', array());

        return parent::getNrefrEtat();
    }

}
