<?php

namespace Proxies\__CG__\Abi\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsClient extends \Abi\UtilisateurBundle\Entity\AbsClient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'clientId', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'accountNonLocked', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'salt', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'roles', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientRef', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientCivilite', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientNom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'username', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'userfirstname', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientPrenom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientEmail', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientTel', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientCp', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientVille', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientAdresse', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientEtat', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientNewsletter', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientDate', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'password', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'oldPassword', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'confirmationMdp', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'photoProfil', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'photoProfilModifier', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'estEfface', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'estValide');
        }

        return array('__isInitialized__', 'clientId', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'accountNonLocked', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'salt', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'roles', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientRef', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientCivilite', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientNom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'username', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'userfirstname', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientPrenom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientEmail', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientTel', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientCp', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientVille', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientAdresse', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientEtat', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientNewsletter', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'clientDate', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'password', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'oldPassword', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'confirmationMdp', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'photoProfil', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'photoProfilModifier', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'estEfface', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\AbsClient' . "\0" . 'estValide');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsClient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getClientId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getClientId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientId', array());

        return parent::getClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientId', array($id));

        return parent::setClientId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientRef', array());

        return parent::getClientRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientRef($clientRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientRef', array($clientRef));

        return parent::setClientRef($clientRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientCivilite', array());

        return parent::getClientCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientCivilite($clientCivilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientCivilite', array($clientCivilite));

        return parent::setClientCivilite($clientCivilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientNom', array());

        return parent::getClientNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientNom($clientNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientNom', array($clientNom));

        return parent::setClientNom($clientNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientPrenom', array());

        return parent::getClientPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientPrenom($clientPrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientPrenom', array($clientPrenom));

        return parent::setClientPrenom($clientPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientEmail', array());

        return parent::getClientEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientEmail($clientEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientEmail', array($clientEmail));

        return parent::setClientEmail($clientEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientTel', array());

        return parent::getClientTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientTel($clientTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientTel', array($clientTel));

        return parent::setClientTel($clientTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientCp', array());

        return parent::getClientCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientCp($clientCp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientCp', array($clientCp));

        return parent::setClientCp($clientCp);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientVille', array());

        return parent::getClientVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientVille($clientVille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientVille', array($clientVille));

        return parent::setClientVille($clientVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAdresse', array());

        return parent::getClientAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientAdresse($clientAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientAdresse', array($clientAdresse));

        return parent::setClientAdresse($clientAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientEtat', array());

        return parent::getClientEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientEtat($clientEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientEtat', array($clientEtat));

        return parent::setClientEtat($clientEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientNewsletter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientNewsletter', array());

        return parent::getClientNewsletter();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientNewsletter($clientNewsletter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientNewsletter', array($clientNewsletter));

        return parent::setClientNewsletter($clientNewsletter);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientDate', array());

        return parent::getClientDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientDate($clientDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientDate', array($clientDate));

        return parent::setClientDate($clientDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserfirstname($userfirstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserfirstname', array($userfirstname));

        return parent::setUserfirstname($userfirstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserfirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserfirstname', array());

        return parent::getUserfirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', array($mail));

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array());

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function Bloquer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'Bloquer', array());

        return parent::Bloquer();
    }

    /**
     * {@inheritDoc}
     */
    public function Debloquer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'Debloquer', array());

        return parent::Debloquer();
    }

    /**
     * {@inheritDoc}
     */
    public function Effacer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'Effacer', array());

        return parent::Effacer();
    }

    /**
     * {@inheritDoc}
     */
    public function Valider($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'Valider', array($role));

        return parent::Valider($role);
    }

    /**
     * {@inheritDoc}
     */
    public function uploadPhotoProfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadPhotoProfil', array());

        return parent::uploadPhotoProfil();
    }

    /**
     * {@inheritDoc}
     */
    public function uploadPhotoProfilModifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadPhotoProfilModifier', array());

        return parent::uploadPhotoProfilModifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatString', array());

        return parent::getEtatString();
    }

    /**
     * {@inheritDoc}
     */
    public function estADeBloquer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'estADeBloquer', array());

        return parent::estADeBloquer();
    }

    /**
     * {@inheritDoc}
     */
    public function peutValider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'peutValider', array());

        return parent::peutValider();
    }

    /**
     * {@inheritDoc}
     */
    public function peutAjouter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'peutAjouter', array());

        return parent::peutAjouter();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivilege()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivilege', array());

        return parent::getPrivilege();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountNonLocked($accountNonLocked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountNonLocked', array($accountNonLocked));

        return parent::setAccountNonLocked($accountNonLocked);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountNonLocked', array());

        return parent::getAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function estBloque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'estBloque', array());

        return parent::estBloque();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoProfil($photoProfil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoProfil', array($photoProfil));

        return parent::setPhotoProfil($photoProfil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoProfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoProfil', array());

        return parent::getPhotoProfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoProfilModifier($photoProfilModifier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoProfilModifier', array($photoProfilModifier));

        return parent::setPhotoProfilModifier($photoProfilModifier);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoProfilModifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoProfilModifier', array());

        return parent::getPhotoProfilModifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldPassword($oldPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldPassword', array($oldPassword));

        return parent::setOldPassword($oldPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldPassword', array());

        return parent::getOldPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationMdp($confirmationMdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationMdp', array($confirmationMdp));

        return parent::setConfirmationMdp($confirmationMdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getconfirmationMdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getconfirmationMdp', array());

        return parent::getconfirmationMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstEfface($estEfface)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstEfface', array($estEfface));

        return parent::setEstEfface($estEfface);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstEfface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstEfface', array());

        return parent::getEstEfface();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstValide($estValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstValide', array($estValide));

        return parent::setEstValide($estValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstValide', array());

        return parent::getEstValide();
    }

    /**
     * {@inheritDoc}
     */
    public function getSocieteFromRequest($societeRepository)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocieteFromRequest', array($societeRepository));

        return parent::getSocieteFromRequest($societeRepository);
    }

}
