<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsMessagerecu extends \Abi\RoutineBundle\Entity\AbsMessagerecu implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgCivilite', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgNom', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgPrenom', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgEmail', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgTel', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgObjet', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgMessage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgCivilite', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgNom', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgPrenom', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgEmail', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgTel', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgObjet', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgMessage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsMessagerecu' . "\0" . 'msgDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsMessagerecu $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMsgId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMsgId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgId', array());

        return parent::getMsgId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgCivilite($msgCivilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgCivilite', array($msgCivilite));

        return parent::setMsgCivilite($msgCivilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgCivilite', array());

        return parent::getMsgCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgNom($msgNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgNom', array($msgNom));

        return parent::setMsgNom($msgNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgNom', array());

        return parent::getMsgNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgPrenom($msgPrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgPrenom', array($msgPrenom));

        return parent::setMsgPrenom($msgPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgPrenom', array());

        return parent::getMsgPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEmail($msgEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEmail', array($msgEmail));

        return parent::setMsgEmail($msgEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEmail', array());

        return parent::getMsgEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgTel($msgTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgTel', array($msgTel));

        return parent::setMsgTel($msgTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgTel', array());

        return parent::getMsgTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgObjet($msgObjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgObjet', array($msgObjet));

        return parent::setMsgObjet($msgObjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgObjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgObjet', array());

        return parent::getMsgObjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgMessage($msgMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgMessage', array($msgMessage));

        return parent::setMsgMessage($msgMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgMessage', array());

        return parent::getMsgMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgEtat($msgEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgEtat', array($msgEtat));

        return parent::setMsgEtat($msgEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgEtat', array());

        return parent::getMsgEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setMsgDate($msgDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMsgDate', array($msgDate));

        return parent::setMsgDate($msgDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMsgDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMsgDate', array());

        return parent::getMsgDate();
    }

}
