<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DevisPdf extends \Abi\RoutineBundle\Entity\DevisPdf implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfRefclient', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfRefdevis', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfPdf', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfExtension', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfRefclient', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfRefdevis', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfPdf', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfExtension', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\DevisPdf' . "\0" . 'pdfDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DevisPdf $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPdfId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPdfId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfId', array());

        return parent::getPdfId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfRefclient($pdfRefclient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfRefclient', array($pdfRefclient));

        return parent::setPdfRefclient($pdfRefclient);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfRefclient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfRefclient', array());

        return parent::getPdfRefclient();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfRefdevis($pdfRefdevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfRefdevis', array($pdfRefdevis));

        return parent::setPdfRefdevis($pdfRefdevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfRefdevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfRefdevis', array());

        return parent::getPdfRefdevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfPdf($pdfPdf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfPdf', array($pdfPdf));

        return parent::setPdfPdf($pdfPdf);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfPdf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfPdf', array());

        return parent::getPdfPdf();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfExtension($pdfExtension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfExtension', array($pdfExtension));

        return parent::setPdfExtension($pdfExtension);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfExtension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfExtension', array());

        return parent::getPdfExtension();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfEtat($pdfEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfEtat', array($pdfEtat));

        return parent::setPdfEtat($pdfEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfEtat', array());

        return parent::getPdfEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdfDate($pdfDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdfDate', array($pdfDate));

        return parent::setPdfDate($pdfDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdfDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdfDate', array());

        return parent::getPdfDate();
    }

}
