<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsPageModule extends \Abi\RoutineBundle\Entity\AbsPageModule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleRef', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'modulePage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleRef', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'modulePage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageModule' . "\0" . 'moduleEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsPageModule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getModuleId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getModuleId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleId', array());

        return parent::getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleRef($moduleRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleRef', array($moduleRef));

        return parent::setModuleRef($moduleRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleRef', array());

        return parent::getModuleRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setModulePage($modulePage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModulePage', array($modulePage));

        return parent::setModulePage($modulePage);
    }

    /**
     * {@inheritDoc}
     */
    public function getModulePage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModulePage', array());

        return parent::getModulePage();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleTitre($moduleTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleTitre', array($moduleTitre));

        return parent::setModuleTitre($moduleTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleTitre', array());

        return parent::getModuleTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleUrl($moduleUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleUrl', array($moduleUrl));

        return parent::setModuleUrl($moduleUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleUrl', array());

        return parent::getModuleUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleOrdre($moduleOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleOrdre', array($moduleOrdre));

        return parent::setModuleOrdre($moduleOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleOrdre', array());

        return parent::getModuleOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setModuleEtat($moduleEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModuleEtat', array($moduleEtat));

        return parent::setModuleEtat($moduleEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getModuleEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModuleEtat', array());

        return parent::getModuleEtat();
    }

}
