<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsNav extends \Abi\RoutineBundle\Entity\AbsNav implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navType', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navType', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsNav' . "\0" . 'navEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsNav $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNavId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNavId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNavId', array());

        return parent::getNavId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNavTitre($navTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNavTitre', array($navTitre));

        return parent::setNavTitre($navTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNavTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNavTitre', array());

        return parent::getNavTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNavUrl($navUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNavUrl', array($navUrl));

        return parent::setNavUrl($navUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getNavUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNavUrl', array());

        return parent::getNavUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setNavOrdre($navOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNavOrdre', array($navOrdre));

        return parent::setNavOrdre($navOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNavOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNavOrdre', array());

        return parent::getNavOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNavType($navType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNavType', array($navType));

        return parent::setNavType($navType);
    }

    /**
     * {@inheritDoc}
     */
    public function getNavType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNavType', array());

        return parent::getNavType();
    }

    /**
     * {@inheritDoc}
     */
    public function setNavEtat($navEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNavEtat', array($navEtat));

        return parent::setNavEtat($navEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNavEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNavEtat', array());

        return parent::getNavEtat();
    }

}
