<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsPageSidebar extends \Abi\RoutineBundle\Entity\AbsPageSidebar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarRef', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarRef', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSidebar' . "\0" . 'sidebarEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsPageSidebar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSidebarId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSidebarId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSidebarId', array());

        return parent::getSidebarId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSidebarRef($sidebarRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSidebarRef', array($sidebarRef));

        return parent::setSidebarRef($sidebarRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getSidebarRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSidebarRef', array());

        return parent::getSidebarRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setSidebarTitre($sidebarTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSidebarTitre', array($sidebarTitre));

        return parent::setSidebarTitre($sidebarTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSidebarTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSidebarTitre', array());

        return parent::getSidebarTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSidebarDescription($sidebarDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSidebarDescription', array($sidebarDescription));

        return parent::setSidebarDescription($sidebarDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getSidebarDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSidebarDescription', array());

        return parent::getSidebarDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSidebarEtat($sidebarEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSidebarEtat', array($sidebarEtat));

        return parent::setSidebarEtat($sidebarEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getSidebarEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSidebarEtat', array());

        return parent::getSidebarEtat();
    }

}
