<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MdlNosEngagements extends \Abi\RoutineBundle\Entity\MdlNosEngagements implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosEngagements' . "\0" . 'engtsEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MdlNosEngagements $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEngtsId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEngtsId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngtsId', array());

        return parent::getEngtsId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngtsTitre($engtsTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngtsTitre', array($engtsTitre));

        return parent::setEngtsTitre($engtsTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngtsTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngtsTitre', array());

        return parent::getEngtsTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngtsIcon($engtsIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngtsIcon', array($engtsIcon));

        return parent::setEngtsIcon($engtsIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngtsIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngtsIcon', array());

        return parent::getEngtsIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngtsTexte($engtsTexte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngtsTexte', array($engtsTexte));

        return parent::setEngtsTexte($engtsTexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngtsTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngtsTexte', array());

        return parent::getEngtsTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngtsOrdre($engtsOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngtsOrdre', array($engtsOrdre));

        return parent::setEngtsOrdre($engtsOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngtsOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngtsOrdre', array());

        return parent::getEngtsOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setEngtsEtat($engtsEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEngtsEtat', array($engtsEtat));

        return parent::setEngtsEtat($engtsEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEngtsEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEngtsEtat', array());

        return parent::getEngtsEtat();
    }

}
