<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsPageFormulaire extends \Abi\RoutineBundle\Entity\AbsPageFormulaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrSlug', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrRefpage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrType', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrSlug', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrRefpage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrType', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageFormulaire' . "\0" . 'pgflrEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsPageFormulaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPgflrId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPgflrId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPgflrId', array());

        return parent::getPgflrId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPgflrTitre($pgflrTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPgflrTitre', array($pgflrTitre));

        return parent::setPgflrTitre($pgflrTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPgflrTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPgflrTitre', array());

        return parent::getPgflrTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPgflrDescription($pgflrDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPgflrDescription', array($pgflrDescription));

        return parent::setPgflrDescription($pgflrDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getPgflrDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPgflrDescription', array());

        return parent::getPgflrDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPgflrSlug($pgflrSlug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPgflrSlug', array($pgflrSlug));

        return parent::setPgflrSlug($pgflrSlug);
    }

    /**
     * {@inheritDoc}
     */
    public function getPgflrSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPgflrSlug', array());

        return parent::getPgflrSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setPgflrRefpage($pgflrRefpage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPgflrRefpage', array($pgflrRefpage));

        return parent::setPgflrRefpage($pgflrRefpage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPgflrRefpage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPgflrRefpage', array());

        return parent::getPgflrRefpage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPgflrType($pgflrType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPgflrType', array($pgflrType));

        return parent::setPgflrType($pgflrType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPgflrType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPgflrType', array());

        return parent::getPgflrType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPgflrEtat($pgflrEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPgflrEtat', array($pgflrEtat));

        return parent::setPgflrEtat($pgflrEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPgflrEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPgflrEtat', array());

        return parent::getPgflrEtat();
    }

}
