<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MdlNosDocument extends \Abi\RoutineBundle\Entity\MdlNosDocument implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docPdf', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docExtention', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docDate', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docPdf', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docExtention', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docDate', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosDocument' . "\0" . 'docEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MdlNosDocument $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDocId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDocId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocId', array());

        return parent::getDocId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocTitre($docTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocTitre', array($docTitre));

        return parent::setDocTitre($docTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocTitre', array());

        return parent::getDocTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocDescription($docDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocDescription', array($docDescription));

        return parent::setDocDescription($docDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocDescription', array());

        return parent::getDocDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocPdf($docPdf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocPdf', array($docPdf));

        return parent::setDocPdf($docPdf);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocPdf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocPdf', array());

        return parent::getDocPdf();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocExtention($docExtention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocExtention', array($docExtention));

        return parent::setDocExtention($docExtention);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocExtention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocExtention', array());

        return parent::getDocExtention();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocDate($docDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocDate', array($docDate));

        return parent::setDocDate($docDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocDate', array());

        return parent::getDocDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocEtat($docEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocEtat', array($docEtat));

        return parent::setDocEtat($docEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocEtat', array());

        return parent::getDocEtat();
    }

}
