<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsFondimage extends \Abi\RoutineBundle\Entity\AbsFondimage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgColor', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgImage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgRepeat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgAttachment', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgPosition', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgOpacity', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgColor', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgImage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgRepeat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgAttachment', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgPosition', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgOpacity', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsFondimage' . "\0" . 'fondimgEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsFondimage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFondimgId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getFondimgId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgId', array());

        return parent::getFondimgId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFondimgColor($fondimgColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFondimgColor', array($fondimgColor));

        return parent::setFondimgColor($fondimgColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getFondimgColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgColor', array());

        return parent::getFondimgColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFondimgImage($fondimgImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFondimgImage', array($fondimgImage));

        return parent::setFondimgImage($fondimgImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFondimgImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgImage', array());

        return parent::getFondimgImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setFondimgRepeat($fondimgRepeat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFondimgRepeat', array($fondimgRepeat));

        return parent::setFondimgRepeat($fondimgRepeat);
    }

    /**
     * {@inheritDoc}
     */
    public function getFondimgRepeat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgRepeat', array());

        return parent::getFondimgRepeat();
    }

    /**
     * {@inheritDoc}
     */
    public function setFondimgAttachment($fondimgAttachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFondimgAttachment', array($fondimgAttachment));

        return parent::setFondimgAttachment($fondimgAttachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getFondimgAttachment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgAttachment', array());

        return parent::getFondimgAttachment();
    }

    /**
     * {@inheritDoc}
     */
    public function setFondimgPosition($fondimgPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFondimgPosition', array($fondimgPosition));

        return parent::setFondimgPosition($fondimgPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function getFondimgPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgPosition', array());

        return parent::getFondimgPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setFondimgOpacity($fondimgOpacity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFondimgOpacity', array($fondimgOpacity));

        return parent::setFondimgOpacity($fondimgOpacity);
    }

    /**
     * {@inheritDoc}
     */
    public function getFondimgOpacity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgOpacity', array());

        return parent::getFondimgOpacity();
    }

    /**
     * {@inheritDoc}
     */
    public function setFondimgEtat($fondimgEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFondimgEtat', array($fondimgEtat));

        return parent::setFondimgEtat($fondimgEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getFondimgEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFondimgEtat', array());

        return parent::getFondimgEtat();
    }

}
