<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsSlider extends \Abi\RoutineBundle\Entity\AbsSlider implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderImg', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderText', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderUrlTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderInfo', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderImg', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderText', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderUrlTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderInfo', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsSlider' . "\0" . 'sliderDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsSlider $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSliderId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSliderId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderId', array());

        return parent::getSliderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderTitre($sliderTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderTitre', array($sliderTitre));

        return parent::setSliderTitre($sliderTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderTitre', array());

        return parent::getSliderTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderImg($sliderImg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderImg', array($sliderImg));

        return parent::setSliderImg($sliderImg);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderImg', array());

        return parent::getSliderImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderText($sliderText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderText', array($sliderText));

        return parent::setSliderText($sliderText);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderText', array());

        return parent::getSliderText();
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderUrlTitre($sliderUrlTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderUrlTitre', array($sliderUrlTitre));

        return parent::setSliderUrlTitre($sliderUrlTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderUrlTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderUrlTitre', array());

        return parent::getSliderUrlTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderUrl($sliderUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderUrl', array($sliderUrl));

        return parent::setSliderUrl($sliderUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderUrl', array());

        return parent::getSliderUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderInfo($sliderInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderInfo', array($sliderInfo));

        return parent::setSliderInfo($sliderInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderInfo', array());

        return parent::getSliderInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSliderDate($sliderDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSliderDate', array($sliderDate));

        return parent::setSliderDate($sliderDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSliderDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSliderDate', array());

        return parent::getSliderDate();
    }

}
