<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsAdresse extends \Abi\RoutineBundle\Entity\AbsAdresse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'id', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'nomprenom', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'societe', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'email', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'tel1', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'tel2', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'pob', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'fax', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'cp', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'ville', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'adresse', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'heurOverture', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'date');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'id', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'nomprenom', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'societe', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'email', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'tel1', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'tel2', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'pob', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'fax', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'cp', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'ville', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'adresse', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'heurOverture', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsAdresse' . "\0" . 'date');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsAdresse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomprenom($nomprenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomprenom', array($nomprenom));

        return parent::setNomprenom($nomprenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomprenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomprenom', array());

        return parent::getNomprenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setSociete($societe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSociete', array($societe));

        return parent::setSociete($societe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSociete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSociete', array());

        return parent::getSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel1($tel1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel1', array($tel1));

        return parent::setTel1($tel1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel1', array());

        return parent::getTel1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel2($tel2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel2', array($tel2));

        return parent::setTel2($tel2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel2', array());

        return parent::getTel2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPob($pob)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPob', array($pob));

        return parent::setPob($pob);
    }

    /**
     * {@inheritDoc}
     */
    public function getPob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPob', array());

        return parent::getPob();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', array($cp));

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', array());

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeurOverture($heurOverture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeurOverture', array($heurOverture));

        return parent::setHeurOverture($heurOverture);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeurOverture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeurOverture', array());

        return parent::getHeurOverture();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

}
