<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsPageSite extends \Abi\RoutineBundle\Entity\AbsPageSite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageTitle', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageMotcles', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageInfo', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageType', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageTitle', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageMotcles', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageInfo', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageType', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsPageSite' . "\0" . 'pageDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsPageSite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPageId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPageId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageId', array());

        return parent::getPageId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageTitle($pageTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageTitle', array($pageTitle));

        return parent::setPageTitle($pageTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageTitle', array());

        return parent::getPageTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageDescription($pageDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageDescription', array($pageDescription));

        return parent::setPageDescription($pageDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageDescription', array());

        return parent::getPageDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageMotcles($pageMotcles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageMotcles', array($pageMotcles));

        return parent::setPageMotcles($pageMotcles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageMotcles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageMotcles', array());

        return parent::getPageMotcles();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageUrl($pageUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageUrl', array($pageUrl));

        return parent::setPageUrl($pageUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageUrl', array());

        return parent::getPageUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageTexte($pageTexte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageTexte', array($pageTexte));

        return parent::setPageTexte($pageTexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageTexte', array());

        return parent::getPageTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageInfo($pageInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageInfo', array($pageInfo));

        return parent::setPageInfo($pageInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageInfo', array());

        return parent::getPageInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageType($pageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageType', array($pageType));

        return parent::setPageType($pageType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageType', array());

        return parent::getPageType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageEtat($pageEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageEtat', array($pageEtat));

        return parent::setPageEtat($pageEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageEtat', array());

        return parent::getPageEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageDate($pageDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageDate', array($pageDate));

        return parent::setPageDate($pageDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageDate', array());

        return parent::getPageDate();
    }

}
