<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mdnosoffres extends \Abi\RoutineBundle\Entity\Mdnosoffres implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offRefart', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offRefart', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offDescription', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\Mdnosoffres' . "\0" . 'offDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mdnosoffres $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOffId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOffId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffId', array());

        return parent::getOffId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffRefart($offRefart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffRefart', array($offRefart));

        return parent::setOffRefart($offRefart);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffRefart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffRefart', array());

        return parent::getOffRefart();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffDescription($offDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffDescription', array($offDescription));

        return parent::setOffDescription($offDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffDescription', array());

        return parent::getOffDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffEtat($offEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffEtat', array($offEtat));

        return parent::setOffEtat($offEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffEtat', array());

        return parent::getOffEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffDate($offDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffDate', array($offDate));

        return parent::setOffDate($offDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffDate', array());

        return parent::getOffDate();
    }

}
