<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MdlNosSlogants extends \Abi\RoutineBundle\Entity\MdlNosSlogants implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNosSlogants' . "\0" . 'slogEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MdlNosSlogants $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSlogId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSlogId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlogId', array());

        return parent::getSlogId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlogTitre($slogTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlogTitre', array($slogTitre));

        return parent::setSlogTitre($slogTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlogTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlogTitre', array());

        return parent::getSlogTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlogIcon($slogIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlogIcon', array($slogIcon));

        return parent::setSlogIcon($slogIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlogIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlogIcon', array());

        return parent::getSlogIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlogTexte($slogTexte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlogTexte', array($slogTexte));

        return parent::setSlogTexte($slogTexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlogTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlogTexte', array());

        return parent::getSlogTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlogOrdre($slogOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlogOrdre', array($slogOrdre));

        return parent::setSlogOrdre($slogOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlogOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlogOrdre', array());

        return parent::getSlogOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlogEtat($slogEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlogEtat', array($slogEtat));

        return parent::setSlogEtat($slogEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlogEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlogEtat', array());

        return parent::getSlogEtat();
    }

}
