<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MdlNews extends \Abi\RoutineBundle\Entity\MdlNews implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsDescrition', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsDetaille', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsSlug', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsDescrition', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsDetaille', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsSlug', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsEtat', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlNews' . "\0" . 'newsDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MdlNews $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNewsId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNewsId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsId', array());

        return parent::getNewsId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsTitre($newsTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsTitre', array($newsTitre));

        return parent::setNewsTitre($newsTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsTitre', array());

        return parent::getNewsTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsDescrition($newsDescrition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsDescrition', array($newsDescrition));

        return parent::setNewsDescrition($newsDescrition);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsDescrition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsDescrition', array());

        return parent::getNewsDescrition();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsDetaille($newsDetaille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsDetaille', array($newsDetaille));

        return parent::setNewsDetaille($newsDetaille);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsDetaille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsDetaille', array());

        return parent::getNewsDetaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsSlug($newsSlug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsSlug', array($newsSlug));

        return parent::setNewsSlug($newsSlug);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsSlug', array());

        return parent::getNewsSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsEtat($newsEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsEtat', array($newsEtat));

        return parent::setNewsEtat($newsEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsEtat', array());

        return parent::getNewsEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsDate($newsDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsDate', array($newsDate));

        return parent::setNewsDate($newsDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsDate', array());

        return parent::getNewsDate();
    }

}
