<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MdlCompteur extends \Abi\RoutineBundle\Entity\MdlCompteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compCompteur', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compCompteur', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlCompteur' . "\0" . 'compEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MdlCompteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCompId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCompId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompId', array());

        return parent::getCompId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompTitre($compTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompTitre', array($compTitre));

        return parent::setCompTitre($compTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompTitre', array());

        return parent::getCompTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompIcon($compIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompIcon', array($compIcon));

        return parent::setCompIcon($compIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompIcon', array());

        return parent::getCompIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompCompteur($compCompteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompCompteur', array($compCompteur));

        return parent::setCompCompteur($compCompteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompCompteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompCompteur', array());

        return parent::getCompCompteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompOrdre($compOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompOrdre', array($compOrdre));

        return parent::setCompOrdre($compOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompOrdre', array());

        return parent::getCompOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompEtat($compEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompEtat', array($compEtat));

        return parent::setCompEtat($compEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompEtat', array());

        return parent::getCompEtat();
    }

}
