<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MdlTarification extends \Abi\RoutineBundle\Entity\MdlTarification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfIcon', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfTexte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\MdlTarification' . "\0" . 'tarfEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MdlTarification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTarfId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getTarfId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarfId', array());

        return parent::getTarfId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarfTitre($tarfTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarfTitre', array($tarfTitre));

        return parent::setTarfTitre($tarfTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarfTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarfTitre', array());

        return parent::getTarfTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarfIcon($tarfIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarfIcon', array($tarfIcon));

        return parent::setTarfIcon($tarfIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarfIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarfIcon', array());

        return parent::getTarfIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarfTexte($tarfTexte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarfTexte', array($tarfTexte));

        return parent::setTarfTexte($tarfTexte);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarfTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarfTexte', array());

        return parent::getTarfTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarfOrdre($tarfOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarfOrdre', array($tarfOrdre));

        return parent::setTarfOrdre($tarfOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarfOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarfOrdre', array());

        return parent::getTarfOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarfEtat($tarfEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarfEtat', array($tarfEtat));

        return parent::setTarfEtat($tarfEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarfEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarfEtat', array());

        return parent::getTarfEtat();
    }

}
