<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsThemeModule extends \Abi\RoutineBundle\Entity\AbsThemeModule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleInfo', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleTitre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleInfo', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleOrdre', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleUrl', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsThemeModule' . "\0" . 'thModuleEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsThemeModule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getThModuleId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getThModuleId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThModuleId', array());

        return parent::getThModuleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setThModuleTitre($thModuleTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThModuleTitre', array($thModuleTitre));

        return parent::setThModuleTitre($thModuleTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getThModuleTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThModuleTitre', array());

        return parent::getThModuleTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setThModuleInfo($thModuleInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThModuleInfo', array($thModuleInfo));

        return parent::setThModuleInfo($thModuleInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getThModuleInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThModuleInfo', array());

        return parent::getThModuleInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setThModuleOrdre($thModuleOrdre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThModuleOrdre', array($thModuleOrdre));

        return parent::setThModuleOrdre($thModuleOrdre);
    }

    /**
     * {@inheritDoc}
     */
    public function getThModuleOrdre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThModuleOrdre', array());

        return parent::getThModuleOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setThModuleUrl($thModuleUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThModuleUrl', array($thModuleUrl));

        return parent::setThModuleUrl($thModuleUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getThModuleUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThModuleUrl', array());

        return parent::getThModuleUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setThModuleEtat($thModuleEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThModuleEtat', array($thModuleEtat));

        return parent::setThModuleEtat($thModuleEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getThModuleEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThModuleEtat', array());

        return parent::getThModuleEtat();
    }

}
