<?php

namespace Proxies\__CG__\Abi\UtilisateurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClientTemp extends \Abi\UtilisateurBundle\Entity\ClientTemp implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'id', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientRef', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientCivilite', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientNom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientPrenom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientEmail', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientTel', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientCp', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientVille', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientAdresse', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientEtat', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientNewsletter', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientDate');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'id', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientRef', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientCivilite', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientNom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientPrenom', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientEmail', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientTel', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientCp', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientVille', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientAdresse', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientEtat', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientNewsletter', '' . "\0" . 'Abi\\UtilisateurBundle\\Entity\\ClientTemp' . "\0" . 'clientDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClientTemp $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getClientRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientRef', array());

        return parent::getClientRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientRef($clientRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientRef', array($clientRef));

        return parent::setClientRef($clientRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientCivilite', array());

        return parent::getClientCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientCivilite($clientCivilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientCivilite', array($clientCivilite));

        return parent::setClientCivilite($clientCivilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientNom', array());

        return parent::getClientNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientNom($clientNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientNom', array($clientNom));

        return parent::setClientNom($clientNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientPrenom', array());

        return parent::getClientPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientPrenom($clientPrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientPrenom', array($clientPrenom));

        return parent::setClientPrenom($clientPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientEmail', array());

        return parent::getClientEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientEmail($clientEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientEmail', array($clientEmail));

        return parent::setClientEmail($clientEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientTel', array());

        return parent::getClientTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientTel($clientTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientTel', array($clientTel));

        return parent::setClientTel($clientTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientCp', array());

        return parent::getClientCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientCp($clientCp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientCp', array($clientCp));

        return parent::setClientCp($clientCp);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientVille', array());

        return parent::getClientVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientVille($clientVille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientVille', array($clientVille));

        return parent::setClientVille($clientVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAdresse', array());

        return parent::getClientAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientAdresse($clientAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientAdresse', array($clientAdresse));

        return parent::setClientAdresse($clientAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientEtat', array());

        return parent::getClientEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientEtat($clientEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientEtat', array($clientEtat));

        return parent::setClientEtat($clientEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientNewsletter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientNewsletter', array());

        return parent::getClientNewsletter();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientNewsletter($clientNewsletter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientNewsletter', array($clientNewsletter));

        return parent::setClientNewsletter($clientNewsletter);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientDate', array());

        return parent::getClientDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientDate($clientDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientDate', array($clientDate));

        return parent::setClientDate($clientDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
