<?php

namespace Proxies\__CG__\Abi\RoutineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AbsClientCompliment extends \Abi\RoutineBundle\Entity\AbsClientCompliment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompRef', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompSociete', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompNumerovois', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompBatiment', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompEscalier', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompCode1', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompCode2', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompInterphone', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompEtage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompPorte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompRemarque', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompEtat');
        }

        return array('__isInitialized__', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompId', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompRef', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompSociete', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompNumerovois', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompBatiment', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompEscalier', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompCode1', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompCode2', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompInterphone', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompEtage', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompPorte', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompRemarque', '' . "\0" . 'Abi\\RoutineBundle\\Entity\\AbsClientCompliment' . "\0" . 'clcompEtat');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AbsClientCompliment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getClcompId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getClcompId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompId', array());

        return parent::getClcompId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompRef($clcompRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompRef', array($clcompRef));

        return parent::setClcompRef($clcompRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompRef', array());

        return parent::getClcompRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompSociete($clcompSociete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompSociete', array($clcompSociete));

        return parent::setClcompSociete($clcompSociete);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompSociete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompSociete', array());

        return parent::getClcompSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompNumerovois($clcompNumerovois)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompNumerovois', array($clcompNumerovois));

        return parent::setClcompNumerovois($clcompNumerovois);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompNumerovois()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompNumerovois', array());

        return parent::getClcompNumerovois();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompBatiment($clcompBatiment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompBatiment', array($clcompBatiment));

        return parent::setClcompBatiment($clcompBatiment);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompBatiment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompBatiment', array());

        return parent::getClcompBatiment();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompEscalier($clcompEscalier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompEscalier', array($clcompEscalier));

        return parent::setClcompEscalier($clcompEscalier);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompEscalier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompEscalier', array());

        return parent::getClcompEscalier();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompCode1($clcompCode1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompCode1', array($clcompCode1));

        return parent::setClcompCode1($clcompCode1);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompCode1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompCode1', array());

        return parent::getClcompCode1();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompCode2($clcompCode2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompCode2', array($clcompCode2));

        return parent::setClcompCode2($clcompCode2);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompCode2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompCode2', array());

        return parent::getClcompCode2();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompInterphone($clcompInterphone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompInterphone', array($clcompInterphone));

        return parent::setClcompInterphone($clcompInterphone);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompInterphone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompInterphone', array());

        return parent::getClcompInterphone();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompEtage($clcompEtage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompEtage', array($clcompEtage));

        return parent::setClcompEtage($clcompEtage);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompEtage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompEtage', array());

        return parent::getClcompEtage();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompPorte($clcompPorte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompPorte', array($clcompPorte));

        return parent::setClcompPorte($clcompPorte);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompPorte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompPorte', array());

        return parent::getClcompPorte();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompRemarque($clcompRemarque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompRemarque', array($clcompRemarque));

        return parent::setClcompRemarque($clcompRemarque);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompRemarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompRemarque', array());

        return parent::getClcompRemarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setClcompEtat($clcompEtat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClcompEtat', array($clcompEtat));

        return parent::setClcompEtat($clcompEtat);
    }

    /**
     * {@inheritDoc}
     */
    public function getClcompEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClcompEtat', array());

        return parent::getClcompEtat();
    }

}
